import{S as l,i as u}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const d="44071791-e24b31a34b7a75e1ae02e9c2e",f="https://pixabay.com/api/";async function m(r){const o=await fetch(`${f}?key=${d}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true`);if(!o.ok)throw new Error("Failed to fetch images");return o.json()}let i;function p(r){const o=document.querySelector(".gallery");o.innerHTML=r.map(t=>`
    <a href="${t.largeImageURL}" class="gallery-item">
      <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy">
      <div class="info">
        <p><b>Likes:</b> ${t.likes}</p>
        <p><b>Views:</b> ${t.views}</p>
        <p><b>Comments:</b> ${t.comments}</p>
        <p><b>Downloads:</b> ${t.downloads}</p>
      </div>
    </a>`).join(""),i?i.refresh():i=new l(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250})}function a(r){u.error({title:"Error",message:r,position:"topRight"})}function y(){const r=document.querySelector(".gallery");r.innerHTML=""}function h(){console.log("+"),document.querySelector(".div-loader").classList.remove("hidden")}function g(){console.log("-"),setTimeout(()=>{document.querySelector(".div-loader").classList.add("hidden")},2e3)}document.querySelector("#search-form").addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements.searchQuery.value.trim();if(!o){a("Please enter a search query");return}y(),h();try{const t=await m(o);t.hits.length===0?a("Sorry, there are no images matching your search query. Please try again!"):p(t.hits)}catch(t){a(t.message)}finally{g()}});
//# sourceMappingURL=commonHelpers.js.map
