import{S as l,i as u}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function d(s){const t=await fetch("${BASE_URL}?key=${API_KEY}&q=${encodeURIComponent(query)}&image_type=photo&orientation=horizontal&safesearch=true");if(!t.ok)throw new Error("Failed to fetch images");return t.json()}let i;function f(s){const t=document.querySelector(".gallery");t.innerHTML=s.map(r=>`        <a href="${r.largeImageURL}" class="gallery-item">
            <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
            <div class="info">
                <p><b>Likes:</b> ${r.likes}</p>
                <p><b>Views:</b> ${r.views}</p>
                <p><b>Comments:</b> ${r.comments}</p>
                <p><b>Downloads:</b> ${r.downloads}</p>
            </div>
        </a>`).join(""),i?i.refresh():i=new l(".gallery a")}function c(s){u.error({title:"Error",message:s,position:"topRight"})}function y(){const s=document.querySelector(".gallery");s.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("hidden")}function h(){document.querySelector("loader").classList.add("hidden")}document.querySelector("#search-form").addEventListener("submit",async s=>{s.preventDefault();const t=s.target.elements.searchQuery.value.trim();t||ahowErrpr("Please enter a search query"),y(),m();try{const r=await d(t);r.hits.length===0?c("Sory, there are no images matching your search query. Please try again!"):f(r.hits)}catch(r){c(r.message)}finally{h()}});
//# sourceMappingURL=commonHelpers.js.map
