import{S as l,i as u}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const d="44071791-e24b31a34b7a75e1ae02e9c2e",f="https://pixabay.com/api/";async function m(t){const o=await fetch(`${f}?key=${d}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true`);if(!o.ok)throw new Error("Failed to fetch images");return o.json()}let i;function y(t){const o=document.querySelector(".gallery");o.innerHTML=t.map(r=>`        <a href="${r.largeImageURL}" class="gallery-item">
            <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
            <div class="info">
                <p><b>Likes:</b> ${r.likes}</p>
                <p><b>Views:</b> ${r.views}</p>
                <p><b>Comments:</b> ${r.comments}</p>
                <p><b>Downloads:</b> ${r.downloads}</p>
            </div>
        </a>`).join(""),i?i.refresh():i=new l(".gallery a")}function c(t){u.error({title:"Error",message:t,position:"topRight"})}function p(){const t=document.querySelector(".gallery");t.innerHTML=""}function h(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}document.querySelector("#search-form").addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.searchQuery.value.trim();o||ahowErrpr("Please enter a search query"),p(),h();try{const r=await m(o);r.hits.length===0?c("Sory, there are no images matching your search query. Please try again!"):y(r.hits)}catch(r){c(r.message)}finally{g()}});
//# sourceMappingURL=commonHelpers.js.map
